// <auto-generated />
using System;
using MediaMarket.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MediaMarket.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260203202512_UpdateIcoConfiguration")]
    partial class UpdateIcoConfiguration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MediaMarket.DAL.Entities.Offer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Cpt")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeadlineAssetsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal>("DiscountPercent")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Format")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("LastOrderDay")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MediaType")
                        .HasColumnType("integer");

                    b.Property<Guid>("MediaUserId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("MinOrderValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("PricingModel")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Tags")
                        .HasColumnType("integer");

                    b.Property<string>("TechnicalConditionsText")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("TechnicalConditionsUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MediaType")
                        .HasDatabaseName("IX_Offers_MediaType");

                    b.HasIndex("MediaUserId")
                        .HasDatabaseName("IX_Offers_MediaUserId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Offers_Status");

                    b.HasIndex("ValidFrom")
                        .HasDatabaseName("IX_Offers_ValidFrom");

                    b.HasIndex("ValidTo")
                        .HasDatabaseName("IX_Offers_ValidTo");

                    b.HasIndex("MediaType", "Status")
                        .HasDatabaseName("IX_Offers_MediaType_Status");

                    b.HasIndex("Status", "ValidFrom", "ValidTo")
                        .HasDatabaseName("IX_Offers_Status_ValidDates");

                    b.ToTable("Offers", (string)null);
                });

            modelBuilder.Entity("MediaMarket.DAL.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgencyUserId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("CommissionAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("CommissionRate")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<decimal?>("CptSnapshot")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Impressions")
                        .HasColumnType("integer");

                    b.Property<Guid>("MediaUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uuid");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("PreferredFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PreferredTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PricingModelSnapshot")
                        .HasColumnType("integer");

                    b.Property<int?>("QuantityUnits")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("UnitPriceSnapshot")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AgencyUserId")
                        .HasDatabaseName("IX_Orders_AgencyUserId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Orders_CreatedAt");

                    b.HasIndex("MediaUserId")
                        .HasDatabaseName("IX_Orders_MediaUserId");

                    b.HasIndex("OfferId")
                        .HasDatabaseName("IX_Orders_OfferId");

                    b.HasIndex("OrderNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Orders_OrderNumber");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Orders_Status");

                    b.HasIndex("AgencyUserId", "Status")
                        .HasDatabaseName("IX_Orders_AgencyUserId_Status");

                    b.HasIndex("CreatedAt", "Status")
                        .HasDatabaseName("IX_Orders_CreatedAt_Status");

                    b.HasIndex("MediaUserId", "Status")
                        .HasDatabaseName("IX_Orders_MediaUserId_Status");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("MediaMarket.DAL.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ico")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.HasIndex("Role")
                        .HasDatabaseName("IX_Users_Role");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Users_Status");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("MediaMarket.DAL.Entities.Offer", b =>
                {
                    b.HasOne("MediaMarket.DAL.Entities.User", "MediaUser")
                        .WithMany("Offers")
                        .HasForeignKey("MediaUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MediaUser");
                });

            modelBuilder.Entity("MediaMarket.DAL.Entities.Order", b =>
                {
                    b.HasOne("MediaMarket.DAL.Entities.User", "AgencyUser")
                        .WithMany("OrdersAsAgency")
                        .HasForeignKey("AgencyUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediaMarket.DAL.Entities.User", "MediaUser")
                        .WithMany("OrdersAsMedia")
                        .HasForeignKey("MediaUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediaMarket.DAL.Entities.Offer", "Offer")
                        .WithMany("Orders")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AgencyUser");

                    b.Navigation("MediaUser");

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("MediaMarket.DAL.Entities.Offer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("MediaMarket.DAL.Entities.User", b =>
                {
                    b.Navigation("Offers");

                    b.Navigation("OrdersAsAgency");

                    b.Navigation("OrdersAsMedia");
                });
#pragma warning restore 612, 618
        }
    }
}
